repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 3.3.7
    hooks:
      - id: pylint
        stages: [manual]  # Only run when triggered manually
        args: ["--disable=C0114,C0115,C0116"]  # (optional) ignore docstring warning