name: Python CI with Ruff

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff pytest

      - name: Run ruff for python syntax errors and linting
        run: |
          # Only check for syntax errors, undefined names, etc.
          ruff --select=E9,F63,F7,F82 .

      - name: Test with pytest
        run: |
          pytest

